### ISSUE TITLE
Custom trained model output shape 

### ISSUE THREAD

**Issue by SwanandkEN** [SeanAvery/yolov5-tensorrt#10]
In Processor.py I am having a hard time with this error:
  reshaped.append(output.reshape(shape))
ValueError: cannot reshape array of size 134400 into shape (1,3,80,80,85)

How to understand output of trt as size is coming to 134400
Custom trained model has 2 classes

**Comment by SeanAvery** [comment]
Hey @SwanandkEN , right now the code works with input images `3, 640, 640`. This causes the first output to be size `1632000` given the yolov5 strides.

You can either reshape inputs to be 640 by 640, or adjust the hardcoded output shapes. 

This should be configured on the fly by the code. Thank you for creating an issue for it.

**Comment by SwanandkEN** [comment]
I did get that part but in the existing code image is being resized to 640,640 and even being transposed. pre_process function in Processor.py does that.
I am getting an output of 134400 which is not making sense to me, can you please help me in reshaping the tensor i am getting.
I am getting 3 arrays in outputeach of size 134400 as there are 3 objects in the inference image.

**Comment by SeanAvery** [comment]
@SwanandkEN there should be 3 outputs for the various grid sizes
```
1. (80 by 80)
2. (40 by 40)
3. (20 by 20)
```
If all of your output layers are the same size, there could be an issue with your model. I would suggest taking a closer look at your output layers in `netron` to maker sure nothing weird is going on.

**Comment by SeanAvery** [comment]
@SwanandkEN I think you are referring the anchor dimension.

You can think about the output as such:

```
[
(3, 80, 80, 85),
(3, 40, 40, 85),
(3, 20, 20, 85)
]
```


There are `3` output layers in yolov5, one for each grid size.

There are `3` anchor sizes in each output layer. 

There are `x, y` grid dimensions depending on the output layer,

Finally there is the `85` tensor specifying box, confidence, and class scores.

Hope that helps

**Comment by SwanandkEN** [comment]
Thank you for your time and helping me here, i am getting more clearer idea now here, I made a mistaken while understanding output of the three layers.
I am getting output as (134400,), (33600,) (8400,)
I figured out as there are only two classes no of filters used were (2+5)*3, where as in your example its (80+5)*3.
Please consider making this value dynamic.
Thanks a lot again for your help.

**Comment by SeanAvery** [comment]
@SwanandkEN Ah yes, that makes sense. 

Thanks for taking the time to get the code working with custom classes. The code is rough right now... I have been working on other projects the last month. I want to move to `yaml` configs like the yolov5 codebase.

**Comment by ZhangChaoZhong** [comment]
> Thank you for your time and helping me here, i am getting more clearer idea now here, I made a mistaken while understanding output of the three layers.
> I am getting output as (134400,), (33600,) (8400,)
> I figured out as there are only two classes no of filters used were (2+5)*3, where as in your example its (80+5)*3.
> Please consider making this value dynamic.
> Thanks a lot again for your help.

Hello, I have the same problem. Excuse me, can you tell me how to modify it?

**Comment by helloyan** [comment]
wait for answer +1

**Comment by bertinma** [comment]
@SwanandkEN @SeanAvery Getting the same issue. How did you solve it please ?
