### ISSUE TITLE
Inference time seems not correct since the cuda is asynchronized?

### ISSUE THREAD

**Issue by PonyPC** [SeanAvery/yolov5-tensorrt#11]
In 'python/lib/Processor.py'
```
        start = time.time()
        self.context.execute_async_v2(
                bindings=self.bindings,
                stream_handle=self.stream.handle)
        end = time.time()
        print('execution time:', end-start)
```

**Comment by SeanAvery** [comment]
Yes @PonyPC good call! The time bookend should take place after allocating memory from the gpu back to the device, and synchronization has taken place. Will update README so the inference times listed in the README are not misleading. 

https://github.com/SeanAvery/yolov5-tensorrt/blob/master/python/lib/Processor.py#L97

I honestly have not even taken a serious look at speed. 

The first thing I want to do is optimize post-processing and NMS.

Move all numpy ops to pycuda.

**Comment by PonyPC** [comment]
I have test this about 6 fps on jetson nano. Is it a normal speed?
Also how to implement batch-size more than 1 so that can boost?

Is it "yv, xv" or "xv, yv" in:
https://github.com/SeanAvery/yolov5-tensorrt/blob/master/python/lib/Processor.py#L200
Thanks for your great job.
