### ISSUE TITLE
Trt conversion failure

### ISSUE THREAD

**Issue by rodri651** [SeanAvery/yolov5-tensorrt#2]
I'm trying to convert your "lib/models/yolov5s-simple.onnx" model to trt using the export_tensorrt.py file. 
However I meet this error:
```
[TensorRT] VERBOSE: ModelImporter.cpp:90: Importing initializer: 305
In node -1 (parseGraph): UNSUPPORTED_NODE: Assertion failed: convertOnnxWeights(initializer, &weights, ctx)
```

any help debuggin this would be appreciated, thanks!

**Comment by rodri651** [comment]
resolved by using nvcr.io/nvidia/pytorch:20.06-py3 and downgrading pytorch to 1.5.1, torchvision to 0.6.1

**Comment by SeanAvery** [comment]
hey @rodri651 , thanks for trying out the script. 

Hm thats a strange error, it should not require any pytorch installation to run conversion script, only the tensorrt onnx parser. 

The python code right now uses tensorrt, numpy and opencv to load images. Will work on adding a proper `requirements.txt` and setup process to the package.

I am testing out the pytorch code using the ipynb notebook on a google colab instance.
