### ISSUE TITLE
ModuleNotFoundError: No module named 'classes'

### ISSUE THREAD

**Issue by wurongyuan** [SeanAvery/yolov5-tensorrt#3]
Traceback (most recent call last):
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/demo.py", line 3, in <module>
    from Visualizer import Visualizer
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/Visualizer.py", line 8, in <module>
    from classes import coco
ModuleNotFoundError: No module named 'classes'

what's the classes?
how to install it?

**Comment by wurongyuan** [comment]
thank you

**Comment by SeanAvery** [comment]
hey @wurongyuan. Thanks, good catch. Just pushed up the file.

**Comment by wurongyuan** [comment]
I use this to splve the problem.
put the coco into Visualizer.py
coco = ('person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
           'train', 'truck', 'boat', 'traffic_light', 'fire_hydrant',
           'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog',
           'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
           'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
           'skis', 'snowboard', 'sports_ball', 'kite', 'baseball_bat',
           'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket',
           'bottle', 'wine_glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
           'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
           'hot_dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
           'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop',
           'mouse', 'remote', 'keyboard', 'cell_phone', 'microwave',
           'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
           'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush')

**Comment by wurongyuan** [comment]
another problem appears:
setting up Yolov5s-simple.trt processor
[TensorRT] ERROR: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/demo.py", line 33, in <module>
    main()   
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/demo.py", line 7, in main
    processor = Processor()
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/Processor.py", line 17, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

**Comment by SeanAvery** [comment]
ok, looks like the cuda `engine` is not being defined on line https://github.com/SeanAvery/yolov5-tensorrt/blob/master/python/lib/Processor.py#L16. 

could be an issue with relative path to model. Just pushed up a fix to work if you are running the demo script in another directory.

**Comment by wurongyuan** [comment]
> ok, looks like the cuda `engine` is not being defined on line https://github.com/SeanAvery/yolov5-tensorrt/blob/master/python/lib/Processor.py#L16.
> 
> could be an issue with relative path to model. Just pushed up a fix to work if you are running the demo script in another directory.
I use your new code
`TRTbin = '{}/models/yolov5s-simple.trt'.format(os.path.dirname(__file__))`
which doesn't solve the problem.
It also gets this....
```
[TensorRT] ERROR: coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/demo.py", line 33, in <module>
    main()   
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/demo.py", line 7, in main
    processor = Processor()
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/Processor.py", line 19, in __init__
    self.context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

**Comment by SeanAvery** [comment]
Ah looks to be an issue with deserializing the trt engine file.

Can you changing the trt logger to verbose mode here
https://github.com/SeanAvery/yolov5-tensorrt/blob/master/python/lib/Processor.py#L14
to `trt.Logger.VERBOSE`

**Comment by wurongyuan** [comment]
I have tried the folowing code:
```
TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
TRT_LOGGER = trt.Logger()
```
which doesn't help.
I guees that your .trt file seems wrong.
I use the trtexec to convert the v5 .onnx file(from yolov5s.pth, batch=1) to  .engine file and put it at
`TRTbin = 'models/yolov5_1.engine'`
it doesn't display the error above, however, it get the new issue.
```
setting up Yolov5s-simple.trt processor
original image shape (334, 500, 3)
Traceback (most recent call last):
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/demo.py", line 33, in <module>
    main()   
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/demo.py", line 15, in main
    output = processor.detect(img) 
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/Processor.py", line 85, in detect
    outputs = self.inference(resized)
  File "/home/wry/PycharmProjects/yolov5_trt_SeanAvary/python/lib/Processor.py", line 107, in inference
    cuda.memcpy_htod_async(inp['device'], inp['host'], self.stream)
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument 
```

**Comment by SeanAvery** [comment]
hm. Can you provide me with more information on your OS and TensorRT version.

I am running on Jetpack 4.2, TensorRT v7

**Comment by wurongyuan** [comment]
> hm. Can you provide me with more information on your OS and TensorRT version.
> 
> I am running on Jetpack 4.2, TensorRT v7

ubuntu 16.04
TensorRT 7.1

**Comment by SeanAvery** [comment]
@wurongyuan. Looks to me like there are some dependency issues going on. Going to be working on adding a proper dependency setup script and perhaps a container to run things inside.

**Comment by wurongyuan** [comment]
> @wurongyuan. Looks to me like there are some dependency issues going on. Going to be working on adding a proper dependency setup script and perhaps a container to run things inside.

can u give a specificnum

**Comment by wurongyuan** [comment]
> > @wurongyuan. Looks to me like there are some dependency issues going on. Going to be working on adding a proper dependency setup script and perhaps a container to run things inside.
> 
> can u give a specificnum



> @wurongyuan. Looks to me like there are some dependency issues going on. Going to be working on adding a proper dependency setup script and perhaps a container to run things inside.

can u give a list to record the time between using TensorRT and not using it?

**Comment by SeanAvery** [comment]
@wurongyua here is the inference time on the model I am using.

| model  | input size |  time (ms)   |
| ------------- | ------------- | ----------|
| small-simple  | 640x640x3  | 15.46 |

Note that this is just the inference time for the raw yolo output. The postprocessing and nms thresholding also take up a significant amount of time. 

The detection and forward pass in yolov5 pytorch repo uses torch ops and torchvision to post process. The nms is run on the gpu using torchvision making it quite fast.

Right now my repo uses numpy ops which run on the cpu, in the future I am planning to rewrite the numpy ops in pycuda to get the fastest possible time.

**Comment by SeanAvery** [comment]
| model  |  fp precision  | input size |  time (ms)   |
| ------------- | ------------- | ---------- | ---- |
| small-simple  |  32  |  640x640x3  | 15.46 |
| small-simple  |  16  |  640x640x3  | 9.47  |
