### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'yolov5/yolov5s.onnx'

### ISSUE THREAD

**Issue by NewPenguin** [SeanAvery/yolov5-tensorrt#5]
Please pardon my stupidity as i am really new to this, 
As i ran the ipynb file I hit a FileNotFoundError.

![image](https://user-images.githubusercontent.com/50839211/91142895-34bdb000-e6e4-11ea-92b3-bb2766124fe5.png)

I am assuming the file is actually yolov5s.pt file ?

**Comment by GuiSteffen** [comment]
You cannot just run that cell.
You need to run previous cells to transform your .pt file in .onnx

This last cell you are trying to run is to display the model using netron

**Comment by SeanAvery** [comment]
hey @NewPenguin , where you able to get netron working

Unfortunately in Google Colab, you cannot just open up ports. 

I had this hack for setting up proxy.

```
from google.colab.output import eval_js
eval_js("google.colab.kernel.proxyPort(3344)")
```

It appears to not be working anymore, will report back if I fix this issue.

If you want to view the onnx model with netron, you can also go to the file tree and download to your local machine.

**Comment by NewPenguin** [comment]
> hey @NewPenguin , where you able to get netron working?
> 
> Unfortunately in Google Colab, you cannot just open up ports.
> 
> I had this hack for setting up proxy.
> 
> ```
> from google.colab.output import eval_js
> eval_js("google.colab.kernel.proxyPort(3344)")
> ```
> 
> It appears to not be working anymore, will report back if I fix this issue.
> 
> If you want to view the onnx model with netron, you can also go to the file tree and download to your local machine.

So sorry for the late reply, as i have not try it out yet, but i do not seem to run into that problem :0
