### ISSUE TITLE
Slow Video Capture - GStreamer

### ISSUE THREAD

**Issue by GuiSteffen** [SeanAvery/yolov5-tensorrt#6]
I was wondering how are you capturing the video from the Jetson Nano camera?

I am currently using GStreamer but I am getting bad results (FPS) since it is using CPU.

Do you have a code to capture the camera video?

**Comment by SeanAvery** [comment]
@GuiSteffen Yes, simply using the `nvarguscamerasrc` gstreamer plugin. You can get hardware accelerated csi camera capture. 

A very simple setup is to use opencv VideoCapture with gstreamer pipeline and the capture is fast.

Here is an example: 
https://github.com/SeanAvery/async-tensorrt/blob/master/stream.py#L36

I am currently working on revamping my CSI camera stream to get rid of opencv dependency. 
The jetson-inference repository by dustynv has great code for doing camera capture

https://github.com/dusty-nv/jetson-utils/blob/master/camera/gstCamera.cpp

I am working on porting the code into a smaller library here:
https://github.com/SeanAvery/gst-cam

**Comment by GuiSteffen** [comment]
@SeanAvery Thank you for your reply.
I am in fact using Gstreamer and Opencv VideoCapture pipeline... But the camera seems a bit slow and uses too much CPU.

I will have a look at these options shortly since I am now focusing on the inference time of this version.

If you dont mind me asking, I wonder if you think reaching around 15 FPS on a nano is even possible using yolov5 m weights. I have bought a nano and I am now thinking that I underestimated the computational requirements of the model. I am only reaching around 3.5 FPS. (Using PyTorch) and around the same using TRT (For now).

Appreciate your time. Thank you.

**Comment by SeanAvery** [comment]
@GuiSteffen Interesting. if you have any metrics on the python OpenCV VideoCapture please share. I have been worried about latency there but I am pretty sure the VideoCapture is simply handling memory assignment from the gstreamer appsink. 

I found that my out of the box opencv imshow display is incredibly slow. I know there is an opengl backend but I forgot to build my opencv with opengl support and it takes all day to rebuild...

Overall I am finding opencv to be too clunky and big for real time stuff.
